name: json2file
description: Generate file output from JSON
author: jackton1
inputs:
  directory:
    description: "Directory to write to"
    required: true
    default: ".github/outputs"
  outputs:
    description: "JSON string"
    required: true
  keys:
    description: "List of Keys to read from the `outputs` JSON string"
    required: true
  skip_missing_keys:
    description: "Skip missing keys not found in the `outputs` JSON string"
    required: false
    default: "false"
  extension:
    description: "File extension to use"
    required: false
    default: "txt"

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: file-text
  color: white
